server:
  port: 8080
  servlet:
    context-path: /


# 配置日志
logging:
  level:
    com: debug

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/panda
    username: root
    password: root
  #配置redis
  redis:
    host: localhost # 主机
    port: 6379      # 端口
mybatis:
  #别名扫描
  type-aliases-package: com.panda.sport.manager
  #开启下划线与小驼峰映射
  configuration:
    map-underscore-to-camel-case: true
    #开启sql语句的日志记录
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #指定mapper.xml文件的位置
  mapper-locations:
    - classpath:mapper/*.xml







#简单类型的数据
my:
  host: localhost
  port: 6379
  #引用类型数据
  user:
    id: 110
    name: 狗娃
    age: 18
  #数组类型
  address:
    - 广州
    - 湛江
    - 东莞
  #数组引用类型  存储一个个user对象
  userList:
    - id: 110
      name: 狗娃
      age: 18
    - id: 220
      name: 狗剩
      age: 20
    - id: 330
      name: 铁蛋
      age: 30